name: Package Project

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Create version file
      run: |
        echo "$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" > version.txt
        echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV  # Store version for later
    
    - name: Install zip utility
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
    
    - name: Create project package
      run: |
        zip -r hunchbank-project-${{ env.VERSION }}.zip . -x "*.git*" "*.github*" "*.gitignore" "*.DS_Store"
    
    - name: Create Release and Upload Artifact
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "latest"  # Always use "latest" tag
        name: "Latest Build"
        body: "Auto-generated build from ${{ github.sha }} on ${{ github.event.head_commit.message }}"
        files: hunchbank-project-${{ env.VERSION }}.zip
        overwrite: true  # Overwrite the "latest" tag on each push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload artifact (optional fallback)
      uses: actions/upload-artifact@v4
      with:
        name: hunchbank-project-${{ github.sha }}
        path: hunchbank-project-${{ env.VERSION }}.zip
        retention-days: 30